name: Release

on:
  release:
    types: [published]

jobs:
  release_zip_file:
    name: Prepare release asset
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: ZIP Component Dir
        run: |
          cd custom_components/cloudflared_tunnel
          zip cloudflared_tunnel.zip -r ./

      - name: Upload zip to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: custom_components/cloudflared_tunnel/cloudflared_tunnel.zip
          asset_name: cloudflared_tunnel.zip
          tag: ${{ github.ref }}
          overwrite: true
